ALTER TABLE access_keys ADD created TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW();
ALTER TABLE access_keys ADD last_used TIMESTAMP WITH TIME ZONE;

ALTER TABLE branches DROP sort;
ALTER TABLE branches ADD last_used TIMESTAMP WITH TIME ZONE;
